version: 0.0
os: linux
files:
  - source: /backend
    destination: /home/ubuntu/my-flask-app
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
